### ISSUE TITLE
Multiple keyboards

### ISSUE THREAD

**Issue by coffebar** [MahouShoujoMivutilde/hyprland-per-window-layout#2]
I think it's a common situation when people have external keyboard connected to laptop. 
So we need to have an option to setup Multiple keyboards.
Also it's possible to use same dotfiles on different machines and in this case single hardcoded keyboard is not working. 

What do you think about changing layouts on every connected keyboards without any configuration? I mean to switch them all in loop

**Comment by Hi-Angel** [comment]
Why you closed it? I just found this project and I too find it odd that it requires to move keyboard configuration from `input` to `device`. Like, I can't comfortably use hyprland without per-window layout, but neither it seems okay to have to modify the config every time I connect new keyboard.

**Comment by Hi-Angel** [comment]
Oh, I see, [you wrote your own implementation in Rust!](https://github.com/coffebar/hyprland-per-window-layout). Oddly, Google does not give your Github, but it gave page on docs.rs instead.

Thank you, works for me!

**Comment by coffebar** [comment]
I was thinking you want to restore the issue in my repo. I didn't read carefully.

**Comment by Hi-Angel** [comment]
> I was thinking you want to restore the issue in my repo. I didn't read carefully.

Well, your version of the plugin does work with `input` 😊
