### ISSUE TITLE
Use a default layout for new windows

### ISSUE THREAD

**Issue by akdevservices** [MahouShoujoMivutilde/hyprland-per-window-layout#3]
Use a default layout (not the current one) for new windows. It can be the first layout in `kb_layout = us, ua, fr`, i. e. `us`. If you like the current script behaviour, it would be nice to have an additional config option to specify the default layout.

**Comment by MahouShoujoMivutilde** [comment]
Implemented in https://github.com/MahouShoujoMivutilde/hyprland-per-window-layout/commit/0c2a268d561f3083532fc85da9a45629cfb7f245.

Launch with `exec-once = HPWX_PREFER_FIRST=true hyprland-per-window-xkblayout`

**Comment by akdevservices** [comment]
> Launch with `exec-once = HPWX_PREFER_FIRST=true hyprland-per-window-xkblayout`

I have already made a enhancement, which allows to specify any layout as default via config :) The patch is below (to commit 6a82e3d). I think it's more flexible and elegant way to implement a default layout for new windows. Just add default_layout="us" (or any layout you want) to `~/.config/hypr/xkb_layout.conf`.
[default-layout.patch.tar.gz](https://github.com/MahouShoujoMivutilde/hyprland-per-window-layout/files/12368055/default-layout.patch.tar.gz)

**Comment by MahouShoujoMivutilde** [comment]
I just didn't want to deal with validation for a user possibly specifying wrong layout (that is - not declared in hyprland config) as default. 

Well, good thing about shell scripts is how hackable they are :)
